version: '2'
services:
  webserv:
    container_name: webservice
    logging:
      driver: "gelf"
      options:
        gelf-address: udp://localhost:12201
    build: .
    network_mode: "host"
    depends_on:
      - elk

  webserv_1:
    container_name: webservice_1
    logging:
      driver: "gelf"
      options:
        gelf-address: udp://localhost:12201
    build: .
    network_mode: "host"
    environment:
      - server.port=8090
    depends_on:
    - elk

  mongo:
    container_name: mongodb
    image: mongo:3.4
    network_mode: "host"

  elk:
    container_name: ELK
    build: ./docker-for-elk
    volumes:
      - ./logstash.conf:/etc/logstash/conf.d/customlogstash.conf
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
      - "12201:12201/udp"
    network_mode: "host"